#!/usr/bin/env ruby

def main(argv = ARGV.freeze)
  deps_file = File.expand_path(ARGV.fetch(0))

  Dir.chdir("#{ENV['GOPATH'].split(':').first}/src") do
    deps(deps_file).each do |lib,sha1|
      lib_basename = File.basename(lib)
      ensure_cloned(lib, lib_basename)
      ensure_at_sha1(File.join(Dir.pwd, lib_basename), lib, sha1)
    end
  end
end

def deps(deps_file)
  deps_hash = {}

  File.open(deps_file) do |f|
    f.each do |line|
      lib, sha1 = line.split
      deps_hash[lib] = sha1
    end
  end

  deps_hash
end

def ensure_cloned(lib, lib_basename)
  if !File.directory?(lib_basename)
    if !system("git clone git://#{lib}.git")
      abort "Git clone of '#{lib}' failed!"
    end
  end
end


def ensure_at_sha1(libdir, lib, sha1)
  Dir.chdir(libdir) do
    if !system("git reset --hard #{sha1}")
      abort "Resetting '#{lib}' to '#{sha1}' failed!"
    end
  end
end

if $0 == __FILE__
  main(ARGV)
end
